steps:
  # build & push the container image to gcr using kaniko - requires a Dockerfile in same directory
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/IMAGE:latest"]
# Deploys IMAGE to compute engine as *my-instance*
- name: "gcr.io/cloud-builders/gcloud"
  args: ['compute', 'instances', 'create-with-container', 'my-instance', '--container-image', 'gcr.io/$PROJECT_ID/IMAGE:latest']
